services:
  backend:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/app/backend
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
      - POSTGRES_SERVER=db

    command: >
      sh -c "make dev-run"
    ports:
      - "8000:8000"

  migrations:
    environment:
      - POSTGRES_SERVER=db
